// <auto-generated />
using System;
using CarRental.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRental.Api.Migrations
{
    [DbContext(typeof(CarRentalDbContext))]
    [Migration("20260822212115_AddIsFeatured")]
    partial class AddIsFeatured
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarRental.Api.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<string>("Badge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerDay")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReviewsCount")
                        .HasColumnType("int");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            Badge = "Bestseller",
                            Brand = "Porsche",
                            Category = "Sportowe",
                            Description = "Wyjątkowe sportowe coupe stworzone z myślą o maksymalnych osiągach i precyzyjnym prowadzeniu.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/porsche-911-gt3.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "911 GT3",
                            Power = 510,
                            PricePerDay = 1499m,
                            Range = "450 KM",
                            Rating = 4.9000000000000004,
                            ReviewsCount = 32,
                            Seats = 2,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 2,
                            Brand = "Porsche",
                            Category = "Sportowe",
                            Description = "Lekki i dynamiczny samochód sportowy oferujący świetne prowadzenie oraz wyjątkowe wrażenia z jazdy.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/porsche-718-cayman.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "718 Cayman",
                            Power = 300,
                            PricePerDay = 899m,
                            Range = "350 KM",
                            Rating = 4.7999999999999998,
                            ReviewsCount = 24,
                            Seats = 2,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 3,
                            Badge = "Hot",
                            Brand = "BMW",
                            Category = "Sportowe",
                            Description = "Sportowy sedan łączący wysoką moc, agresywną stylistykę i komfort podczas codziennej jazdy.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/bmw-m4.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "M4 Competition",
                            Power = 510,
                            PricePerDay = 999m,
                            Range = "450 KM",
                            Rating = 4.7999999999999998,
                            ReviewsCount = 29,
                            Seats = 4,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 4,
                            Badge = "Premium",
                            Brand = "Mercedes-AMG",
                            Category = "Sportowe",
                            Description = "Luksusowe coupe AMG oferujące imponujące osiągi, komfort i charakterystyczny sportowy charakter.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/mercedes-amg-gt.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "GT",
                            Power = 585,
                            PricePerDay = 1399m,
                            Range = "500 KM",
                            Rating = 4.9000000000000004,
                            ReviewsCount = 18,
                            Seats = 2,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 5,
                            Badge = "Ikona",
                            Brand = "Audi",
                            Category = "Sportowe",
                            Description = "Legendarny supersamochód z silnikiem V10, który zapewnia wyjątkowe osiągi i niezapomniane emocje.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/audi-r8.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "R8 V10",
                            Power = 620,
                            PricePerDay = 1599m,
                            Range = "580 KM",
                            Rating = 4.9000000000000004,
                            ReviewsCount = 41,
                            Seats = 2,
                            Transmission = "Automat",
                            Year = 2023
                        },
                        new
                        {
                            CarId = 6,
                            Badge = "Nowy",
                            Brand = "BMW",
                            Category = "Sedan",
                            Description = "Mocny i komfortowy sedan klasy premium idealny zarówno na długie trasy, jak i dynamiczną jazdę.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/bmw-m5.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "M5 Competition",
                            Power = 625,
                            PricePerDay = 999m,
                            Range = "625 KM",
                            Rating = 4.7999999999999998,
                            ReviewsCount = 37,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 7,
                            Brand = "Mercedes-Benz",
                            Category = "Sedan",
                            Description = "Elegancki sedan AMG łączący sportowe osiągi z wysokim komfortem i nowoczesnymi technologiami.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/mercedes-e53.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "E53 AMG",
                            Power = 435,
                            PricePerDay = 849m,
                            Range = "450 KM",
                            Rating = 4.7000000000000002,
                            ReviewsCount = 21,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 8,
                            Badge = "Bestseller",
                            Brand = "Audi",
                            Category = "Sedan",
                            Description = "Przestronne i niezwykle szybkie auto klasy premium oferujące połączenie praktyczności i osiągów.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/audi-rs6.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "RS6",
                            Power = 600,
                            PricePerDay = 1099m,
                            Range = "550 KM",
                            Rating = 4.9000000000000004,
                            ReviewsCount = 34,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 9,
                            Brand = "BMW",
                            Category = "Sedan",
                            Description = "Dynamiczny sedan BMW oferujący sportowe prowadzenie, wysoką moc i komfort na co dzień.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/bmw-m3.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "M3",
                            Power = 510,
                            PricePerDay = 899m,
                            Range = "450 KM",
                            Rating = 4.7999999999999998,
                            ReviewsCount = 27,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 10,
                            Badge = "Premium",
                            Brand = "Mercedes-Benz",
                            Category = "Sedan",
                            Description = "Luksusowy sedan zapewniający wyjątkowy komfort jazdy, przestronne wnętrze i mocny silnik.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/mercedes-s580.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "S580",
                            Power = 503,
                            PricePerDay = 1299m,
                            Range = "500 KM",
                            Rating = 4.9000000000000004,
                            ReviewsCount = 19,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 11,
                            Badge = "Premium",
                            Brand = "Mercedes-AMG",
                            Category = "SUV",
                            Description = "Ikoniczny SUV AMG łączący luksus, terenowy charakter i imponujące osiągi.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/g63.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "G63",
                            Power = 585,
                            PricePerDay = 1299m,
                            Range = "585 KM",
                            Rating = 4.9000000000000004,
                            ReviewsCount = 45,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 12,
                            Badge = "Hot",
                            Brand = "BMW",
                            Category = "SUV",
                            Description = "Potężny SUV BMW oferujący sportowe osiągi, przestronne wnętrze i wysoki komfort podróżowania.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/bmw-x5m.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "X5 M Competition",
                            Power = 625,
                            PricePerDay = 1099m,
                            Range = "550 KM",
                            Rating = 4.7999999999999998,
                            ReviewsCount = 31,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 13,
                            Brand = "Porsche",
                            Category = "SUV",
                            Description = "Luksusowy SUV Porsche zapewniający doskonałe prowadzenie, komfort oraz wszechstronność.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/porsche-cayenne.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "Cayenne",
                            Power = 353,
                            PricePerDay = 899m,
                            Range = "400 KM",
                            Rating = 4.7999999999999998,
                            ReviewsCount = 28,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 14,
                            Badge = "Bestseller",
                            Brand = "Audi",
                            Category = "SUV",
                            Description = "Sportowy SUV Audi łączący potężny silnik, luksusowe wnętrze i wyjątkową dynamikę.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/audi-rsq8.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "RS Q8",
                            Power = 600,
                            PricePerDay = 1199m,
                            Range = "550 KM",
                            Rating = 4.9000000000000004,
                            ReviewsCount = 26,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 15,
                            Badge = "Ikona",
                            Brand = "Lamborghini",
                            Category = "SUV",
                            Description = "Luksusowy supersuv Lamborghini oferujący ekstremalne osiągi i wyjątkowy charakter.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/lamborghini-urus.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "Urus",
                            Power = 666,
                            PricePerDay = 1999m,
                            Range = "650 KM",
                            Rating = 5.0,
                            ReviewsCount = 17,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2023
                        },
                        new
                        {
                            CarId = 16,
                            Badge = "Premium",
                            Brand = "BMW",
                            Category = "Premium",
                            Description = "Luksusowa limuzyna BMW zapewniająca najwyższy komfort, nowoczesne technologie i dużą moc.",
                            FuelType = "Hybryda",
                            ImageUrl = "/images/cars/bmw-7.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "7 Series",
                            Power = 571,
                            PricePerDay = 999m,
                            Range = "500 KM",
                            Rating = 4.9000000000000004,
                            ReviewsCount = 22,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 17,
                            Brand = "Mercedes-Benz",
                            Category = "Premium",
                            Description = "Flagowy sedan Mercedesa stworzony z myślą o najwyższym poziomie komfortu i elegancji.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/mercedes-s-class.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "S-Class",
                            Power = 435,
                            PricePerDay = 1099m,
                            Range = "500 KM",
                            Rating = 4.9000000000000004,
                            ReviewsCount = 25,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 18,
                            Brand = "Audi",
                            Category = "Premium",
                            Description = "Elegancka limuzyna Audi oferująca komfortowe wnętrze, nowoczesne technologie i spokojną jazdę.",
                            FuelType = "Diesel",
                            ImageUrl = "/images/cars/audi-a8.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "A8",
                            Power = 286,
                            PricePerDay = 799m,
                            Range = "700 KM",
                            Rating = 4.7000000000000002,
                            ReviewsCount = 18,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 19,
                            Badge = "Eco",
                            Brand = "Tesla",
                            Category = "Elektryczne",
                            Description = "Elektryczny sedan o imponujących osiągach i dużym zasięgu, idealny na długie podróże.",
                            FuelType = "Elektryczny",
                            ImageUrl = "/images/cars/tesla-model-s.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "Model S",
                            Power = 670,
                            PricePerDay = 899m,
                            Range = "634 KM",
                            Rating = 4.7999999999999998,
                            ReviewsCount = 36,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 20,
                            Badge = "Eco",
                            Brand = "Tesla",
                            Category = "Elektryczne",
                            Description = "Popularny elektryczny sedan oferujący świetny zasięg, dynamiczną jazdę i nowoczesne technologie.",
                            FuelType = "Elektryczny",
                            ImageUrl = "/images/cars/tesla-model-3.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "Model 3",
                            Power = 513,
                            PricePerDay = 499m,
                            Range = "629 KM",
                            Rating = 4.7000000000000002,
                            ReviewsCount = 42,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 21,
                            Badge = "Eco",
                            Brand = "BMW",
                            Category = "Elektryczne",
                            Description = "Sportowy samochód elektryczny BMW łączący dynamiczne osiągi z komfortem codziennego użytkowania.",
                            FuelType = "Elektryczny",
                            ImageUrl = "/images/cars/bmw-i4.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "i4 M50",
                            Power = 544,
                            PricePerDay = 699m,
                            Range = "510 KM",
                            Rating = 4.7999999999999998,
                            ReviewsCount = 23,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 22,
                            Badge = "Premium",
                            Brand = "Porsche",
                            Category = "Elektryczne",
                            Description = "Elektryczne Porsche oferujące sportowe osiągi, luksusowe wnętrze i szybkie ładowanie.",
                            FuelType = "Elektryczny",
                            ImageUrl = "/images/cars/porsche-taycan.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "Taycan 4S",
                            Power = 571,
                            PricePerDay = 899m,
                            Range = "512 KM",
                            Rating = 4.9000000000000004,
                            ReviewsCount = 21,
                            Seats = 4,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 23,
                            Badge = "Bestseller",
                            Brand = "Volkswagen",
                            Category = "Kompaktowe",
                            Description = "Sportowy kompakt idealny do codziennej jazdy, oferujący dynamiczne prowadzenie i praktyczne wnętrze.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/vw-golf-gti.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "Golf GTI",
                            Power = 265,
                            PricePerDay = 399m,
                            Range = "450 KM",
                            Rating = 4.7000000000000002,
                            ReviewsCount = 35,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 24,
                            Brand = "Audi",
                            Category = "Kompaktowe",
                            Description = "Elegancki kompakt Audi łączący komfort, nowoczesne technologie i ekonomiczną jazdę.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/audi-a3.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "A3",
                            Power = 150,
                            PricePerDay = 349m,
                            Range = "500 KM",
                            Rating = 4.5999999999999996,
                            ReviewsCount = 29,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 25,
                            Brand = "BMW",
                            Category = "Kompaktowe",
                            Description = "Kompaktowe BMW oferujące dynamiczną jazdę, komfortowe wnętrze i sportowy charakter.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/bmw-1.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "120i",
                            Power = 178,
                            PricePerDay = 369m,
                            Range = "480 KM",
                            Rating = 4.5999999999999996,
                            ReviewsCount = 20,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 26,
                            Badge = "Eco",
                            Brand = "Toyota",
                            Category = "Sedan",
                            Description = "Komfortowy sedan hybrydowy zapewniający niskie zużycie paliwa i wygodę podczas długich podróży.",
                            FuelType = "Hybryda",
                            ImageUrl = "/images/cars/toyota-camry.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "Camry",
                            Power = 218,
                            PricePerDay = 299m,
                            Range = "800 KM",
                            Rating = 4.5999999999999996,
                            ReviewsCount = 31,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 27,
                            Badge = "Eco",
                            Brand = "Toyota",
                            Category = "SUV",
                            Description = "Wszechstronny SUV hybrydowy oferujący przestronne wnętrze, komfort i ekonomiczną jazdę.",
                            FuelType = "Hybryda",
                            ImageUrl = "/images/cars/toyota-rav4.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "RAV4",
                            Power = 222,
                            PricePerDay = 349m,
                            Range = "750 KM",
                            Rating = 4.7000000000000002,
                            ReviewsCount = 38,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 28,
                            Brand = "Volvo",
                            Category = "SUV",
                            Description = "Elegancki SUV Volvo zapewniający wysoki komfort, bezpieczeństwo i nowoczesny napęd hybrydowy.",
                            FuelType = "Hybryda",
                            ImageUrl = "/images/cars/volvo-xc60.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "XC60",
                            Power = 455,
                            PricePerDay = 549m,
                            Range = "700 KM",
                            Rating = 4.7999999999999998,
                            ReviewsCount = 27,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 29,
                            Badge = "Premium",
                            Brand = "Volvo",
                            Category = "SUV",
                            Description = "Duży SUV premium z przestronnym wnętrzem, siedmioma miejscami i wysokim komfortem podróżowania.",
                            FuelType = "Hybryda",
                            ImageUrl = "/images/cars/volvo-xc90.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "XC90",
                            Power = 455,
                            PricePerDay = 649m,
                            Range = "700 KM",
                            Rating = 4.7999999999999998,
                            ReviewsCount = 24,
                            Seats = 7,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 30,
                            Badge = "Ikona",
                            Brand = "Ford",
                            Category = "Sportowe",
                            Description = "Klasyczny amerykański muscle car oferujący mocny silnik, charakterystyczny wygląd i sportowe emocje.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/ford-mustang.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "Mustang GT",
                            Power = 480,
                            PricePerDay = 699m,
                            Range = "500 KM",
                            Rating = 4.7999999999999998,
                            ReviewsCount = 39,
                            Seats = 4,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 31,
                            Brand = "Ford",
                            Category = "SUV",
                            Description = "Przestronny SUV idealny dla większej grupy pasażerów, oferujący siedem miejsc i wysoki komfort.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/ford-explorer.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "Explorer",
                            Power = 300,
                            PricePerDay = 449m,
                            Range = "600 KM",
                            Rating = 4.5999999999999996,
                            ReviewsCount = 19,
                            Seats = 7,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 32,
                            Badge = "Premium",
                            Brand = "Range Rover",
                            Category = "SUV",
                            Description = "Luksusowy SUV oferujący doskonały komfort, wysoką jakość wykonania i możliwości na długie trasy.",
                            FuelType = "Diesel",
                            ImageUrl = "/images/cars/range-rover-sport.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "Sport",
                            Power = 300,
                            PricePerDay = 999m,
                            Range = "700 KM",
                            Rating = 4.9000000000000004,
                            ReviewsCount = 23,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 33,
                            Badge = "Hot",
                            Brand = "Land Rover",
                            Category = "SUV",
                            Description = "Wszechstronny SUV terenowy łączący luksusowe wnętrze z doskonałymi możliwościami poza asfaltem.",
                            FuelType = "Diesel",
                            ImageUrl = "/images/cars/defender.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "Defender",
                            Power = 300,
                            PricePerDay = 699m,
                            Range = "750 KM",
                            Rating = 4.7999999999999998,
                            ReviewsCount = 30,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 34,
                            Badge = "Eco",
                            Brand = "Lexus",
                            Category = "Premium",
                            Description = "Luksusowy SUV hybrydowy oferujący komfort, nowoczesne technologie i wyjątkową stylistykę.",
                            FuelType = "Hybryda",
                            ImageUrl = "/images/cars/lexus-rx.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "RX 500h",
                            Power = 371,
                            PricePerDay = 599m,
                            Range = "650 KM",
                            Rating = 4.7999999999999998,
                            ReviewsCount = 22,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 35,
                            Badge = "Ikona",
                            Brand = "Lexus",
                            Category = "Sportowe",
                            Description = "Ekskluzywne coupe stworzone dla kierowców ceniących wyjątkowy design, komfort i mocny silnik.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/lexus-lc500.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "LC 500",
                            Power = 477,
                            PricePerDay = 999m,
                            Range = "500 KM",
                            Rating = 4.9000000000000004,
                            ReviewsCount = 16,
                            Seats = 4,
                            Transmission = "Automat",
                            Year = 2023
                        },
                        new
                        {
                            CarId = 36,
                            Brand = "Alfa Romeo",
                            Category = "Sportowe",
                            Description = "Sportowy sedan Alfa Romeo oferujący charakterystyczne włoskie wzornictwo i wyjątkową dynamikę.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/alfa-giulia.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "Giulia Quadrifoglio",
                            Power = 520,
                            PricePerDay = 799m,
                            Range = "500 KM",
                            Rating = 4.7999999999999998,
                            ReviewsCount = 17,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2023
                        },
                        new
                        {
                            CarId = 37,
                            Badge = "Nowy",
                            Brand = "Cupra",
                            Category = "SUV",
                            Description = "Sportowy crossover łączący praktyczność SUV-a z dynamicznym prowadzeniem i nowoczesnym wyglądem.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/cupra-formentor.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "Formentor VZ",
                            Power = 310,
                            PricePerDay = 449m,
                            Range = "500 KM",
                            Rating = 4.7000000000000002,
                            ReviewsCount = 26,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 38,
                            Brand = "Skoda",
                            Category = "Sedan",
                            Description = "Przestronny i komfortowy sedan idealny zarówno do miasta, jak i długich podróży.",
                            FuelType = "Diesel",
                            ImageUrl = "/images/cars/skoda-superb.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "Superb",
                            Power = 193,
                            PricePerDay = 299m,
                            Range = "850 KM",
                            Rating = 4.5999999999999996,
                            ReviewsCount = 44,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 39,
                            Brand = "Volkswagen",
                            Category = "SUV",
                            Description = "Nowoczesny SUV Volkswagena oferujący praktyczne wnętrze, komfort i wszechstronność.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/vw-tiguan.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "Tiguan",
                            Power = 190,
                            PricePerDay = 329m,
                            Range = "600 KM",
                            Rating = 4.5999999999999996,
                            ReviewsCount = 33,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 40,
                            Brand = "Audi",
                            Category = "SUV",
                            Description = "Elegancki SUV Audi zapewniający komfortową jazdę, przestronne wnętrze i wysoką jakość wykonania.",
                            FuelType = "Diesel",
                            ImageUrl = "/images/cars/audi-q5.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "Q5",
                            Power = 204,
                            PricePerDay = 449m,
                            Range = "750 KM",
                            Rating = 4.7000000000000002,
                            ReviewsCount = 29,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 41,
                            Brand = "BMW",
                            Category = "SUV",
                            Description = "Wszechstronny SUV BMW łączący komfort, dynamiczne prowadzenie i praktyczne wnętrze.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/bmw-x3.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "X3",
                            Power = 245,
                            PricePerDay = 449m,
                            Range = "600 KM",
                            Rating = 4.7000000000000002,
                            ReviewsCount = 32,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 42,
                            Brand = "Mercedes-Benz",
                            Category = "SUV",
                            Description = "Nowoczesny SUV Mercedes-Benz oferujący luksusowe wnętrze, komfort i wysoką kulturę jazdy.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/mercedes-glc.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "GLC",
                            Power = 258,
                            PricePerDay = 499m,
                            Range = "600 KM",
                            Rating = 4.7999999999999998,
                            ReviewsCount = 28,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 43,
                            Badge = "Eco",
                            Brand = "Tesla",
                            Category = "Elektryczne",
                            Description = "Praktyczny SUV elektryczny oferujący duży zasięg, przestronne wnętrze i nowoczesne technologie.",
                            FuelType = "Elektryczny",
                            ImageUrl = "/images/cars/tesla-model-y.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "Model Y",
                            Power = 455,
                            PricePerDay = 549m,
                            Range = "533 KM",
                            Rating = 4.7000000000000002,
                            ReviewsCount = 51,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 44,
                            Badge = "Eco",
                            Brand = "Mercedes-Benz",
                            Category = "Elektryczne",
                            Description = "Luksusowy sedan elektryczny oferujący wysoki komfort, duży zasięg i nowoczesne rozwiązania.",
                            FuelType = "Elektryczny",
                            ImageUrl = "/images/cars/mercedes-eqe.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "EQE",
                            Power = 408,
                            PricePerDay = 699m,
                            Range = "590 KM",
                            Rating = 4.7999999999999998,
                            ReviewsCount = 20,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 45,
                            Badge = "Eco",
                            Brand = "Audi",
                            Category = "Elektryczne",
                            Description = "Elektryczny SUV Audi zapewniający komfortową jazdę, przestronne wnętrze i nowoczesny napęd.",
                            FuelType = "Elektryczny",
                            ImageUrl = "/images/cars/audi-q8-etron.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "Q8 e-tron",
                            Power = 408,
                            PricePerDay = 649m,
                            Range = "582 KM",
                            Rating = 4.7000000000000002,
                            ReviewsCount = 18,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 46,
                            Badge = "Ikona",
                            Brand = "Nissan",
                            Category = "Sportowe",
                            Description = "Legendarny sportowy samochód Nissana oferujący ogromną moc i wyjątkowe osiągi.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/nissan-gtr.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "GT-R",
                            Power = 570,
                            PricePerDay = 1199m,
                            Range = "500 KM",
                            Rating = 4.9000000000000004,
                            ReviewsCount = 35,
                            Seats = 4,
                            Transmission = "Automat",
                            Year = 2023
                        },
                        new
                        {
                            CarId = 47,
                            Badge = "Hot",
                            Brand = "Toyota",
                            Category = "Sportowe",
                            Description = "Nowoczesne sportowe coupe Toyoty oferujące świetne prowadzenie, dynamiczny silnik i charakter.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/toyota-supra.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "GR Supra",
                            Power = 340,
                            PricePerDay = 649m,
                            Range = "450 KM",
                            Rating = 4.7999999999999998,
                            ReviewsCount = 28,
                            Seats = 2,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 48,
                            Brand = "Mazda",
                            Category = "Sportowe",
                            Description = "Lekki roadster zapewniający wyjątkową przyjemność z jazdy, szczególnie na krętych drogach.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/mazda-mx5.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "MX-5",
                            Power = 184,
                            PricePerDay = 299m,
                            Range = "450 KM",
                            Rating = 4.7000000000000002,
                            ReviewsCount = 37,
                            Seats = 2,
                            Transmission = "Manual",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 49,
                            Badge = "Eco",
                            Brand = "Renault",
                            Category = "Elektryczne",
                            Description = "Kompaktowy samochód elektryczny oferujący nowoczesne wnętrze, dobry zasięg i komfortową jazdę.",
                            FuelType = "Elektryczny",
                            ImageUrl = "/images/cars/renault-megane.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "Megane E-Tech",
                            Power = 220,
                            PricePerDay = 329m,
                            Range = "450 KM",
                            Rating = 4.5999999999999996,
                            ReviewsCount = 19,
                            Seats = 5,
                            Transmission = "Automat",
                            Year = 2024
                        },
                        new
                        {
                            CarId = 50,
                            Badge = "Nowy",
                            Brand = "Mini",
                            Category = "Kompaktowe",
                            Description = "Stylowy kompakt oferujący dynamiczną jazdę, charakterystyczny design i komfort na co dzień.",
                            FuelType = "Benzyna",
                            ImageUrl = "/images/cars/mini-cooper.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Model = "Cooper S",
                            Power = 204,
                            PricePerDay = 299m,
                            Range = "450 KM",
                            Rating = 4.5999999999999996,
                            ReviewsCount = 23,
                            Seats = 4,
                            Transmission = "Automat",
                            Year = 2024
                        });
                });

            modelBuilder.Entity("CarRental.Api.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReservationId");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("CarRental.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CarRental.Api.Models.Reservation", b =>
                {
                    b.HasOne("CarRental.Api.Models.Car", "Car")
                        .WithMany("Reservations")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRental.Api.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarRental.Api.Models.Car", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("CarRental.Api.Models.User", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
